### ISSUE TITLE
Are linked lists really worth taking up a week?

### ISSUE THREAD

**Issue by ambirdsall** [DevBootcamp-Algorithm-Night/DevBootcamp-Algorithm-Night.github.io#8]
I was talking with @johnakers about this before last night's talk on linked lists. To summarize:

##### Pros
* They are a simpler version of trees, and if you grok implementing `Node` and `LinkedList`, you have a leg up when we go to the more complex version
* They are a bit of an introduction to the broader world of CS—data structures, memory management, etc

##### Cons
* No one is the audience will ever have to actually use them basically ever
* Implementing a linked list in ruby is solving problems that don't exist, which feels weird and pointless
* Far less likely to come up in an interview than trees, which also force you to learn how to implement your own data storage and data organizing structures
* Taking up a week's talk which could arguably be better spent on a different subject

I'm in favor of dropping linked lists from the rotation—either replacing them with a new subject, or just shortening the rotation to 5 subjects, so people get more reps of more useful topics. Right now, when we're sort of resetting the schedule for the New Year, seems like a really opportune time to make this kind of change. Let's find a consensus here and then put up the new schedule when we're on the same page.

(cc: @xjlin0 and @benvogcodes)

**Comment by johnakers** [comment]
Personally, I want to leave them in.

My opinion:

We have been focussing on computer science topics and algorithms for a year+. If we focus solely on aspects that pertain to Web Development, we deny people exposure to a key concept in computer science. In addition, if we remove Linked Lists, a precedent is then set where we may not even need Stacks & Queues or Recursion nights (_nobody will ever make a Stack or Queue class in Ruby or really use Recursion in a Rails app_) and then what are we really left with?

If this happens, the "mission" of Whiteboarding/Algorithm Night completely changes from:

> We'll talk about a fundamental computer science topic and help you tackle some problems on it

to

> Come do some whiteboarding practice and we'll help you

What I want attendees of Algorithm Night to understand is the concept of an algorithm or data structure that is presented. The focus has always been CS related and I feel it should remain that way. In every CS program, Linked Lists are a precursor to Trees, which are a precursor to Graphs.

For those that weren't around during Graphs... it was a failed experiment. Telling people how Breadth and Depth first search work, in the context of a graph, in 15-20 minutes was lost on the vast majority of students as they didn't know what a "Node". Topics do need to be repeated (those searches work on Trees, for instance, but we have to assume students are showing up to every Wednesday night).

Solving problems for the sake of solving problems, without understanding the underlying CS concepts is not what I've aiming for as that's mechanics, which is something that I'm not trying to do. If a student was interested in nothing more, I'd refer them to Interview Cake as Parker has done a great job with that already. Most likely someone that graduates from DBC won't use these traditional concepts but being able to talk about them, in any capacity, is beneficial and introduces a new way of thinking.... the same way students that study Business most likely do not need Calculus but are required to take it at university.

Logistics:

The "curriculum" needs to be 3 or 6 weeks long to coincide with the schedule at DBC and if we were to remove Linked Lists (and potentially more)... something(s) needs to take its place. As mentioned before, I would like the focus to remain "Computer Science in the context of Ruby" related as that is the founding principle of Wednesday nights.

_apologies for the length of this_

**Comment by johnakers** [comment]
@xjlin0 and @benvogcodes,

Just curious as to if you guys have any thoughts?

**Comment by benvogcodes** [comment]
I'm in favor of keeping them. Personally, I found learning about data structures NOT used regularly in Ruby just as enlightening as learning those that are. It helps provide context as to what makes Ruby unique and puts students at a slightly lesser disadvantage when going up against candidates with a traditional CS background.

**Comment by xjlin0** [comment]
I think if Linked List is worthy to talk individually, plus some intro is given on Node.  We don't officially do intro on Node, but it is the very foundation of Linked List, Tree and Graph.
